SC.stringsFor('fr', {
    "_Note": "Notes",
    "_Note_title": "Titre",
    "_Note_title_hint": "Titre de la note",
    "_Note_description": "Description",
    "_Note_description_hint": "Description de la note",
    "_Road": "Routes",
    "_Road_title": "Nom",
    "_Road_title_hint": "Nom de la route",
    "_Road_description": "Description",
    "_Road_description_hint": "Description de la route",
	"_Road_category": "Categorie",
    "_Road_category_hint": "Categorie",
	"_Road_subcategory": "Sous-Categorie",
    "_Road_subcategory_hint": "Sous-Categorie",
	"_Hydro": "Hydrologies",
    "_Hydro_title": "Nom",
    "_Hydro_title_hint": "Nom de l'entité",
    "_Hydro_description": "Description",
    "_Hydro_description_hint": "Description de l'entité",
	"_Hydro_category": "Categorie",
    "_Hydro_category_hint": "Categorie",
	"_Hydro_subcategory": "Sous-Categorie",
    "_Hydro_subcategory_hint": "Sous-Categorie",
	"_Limit": "Limites",
    "_Limit_title": "Nom",
    "_Limit_title_hint": "Nom de la limite",
    "_Limit_description": "Description",
    "_Limit_description_hint": "Description de la limite",
	"_Limit_category": "Categorie",
    "_Limit_category_hint": "Categorie",
	"_Limit_subcategory": "Sous-Categorie",
    "_Limit_subcategory_hint": "Sous-Categorie",
	"_arpenteur_chart": "Arpenteurs",
	"_arpenteur_val_chart": "%@ arpenteurs",
	"_Arpenteur": "Arpenteurs",
	"_Arpenteur_firstname": "Prénom",
	"_Arpenteur_firstname_hint": "Prénom de l'arpenteur",
	"_Arpenteur_lastname": "Nom",
	"_Arpenteur_lastname_hint": "Nom de l'arpenteur",
	"_Arpenteur_postalcode": "Code postal",
	"_Arpenteur_postalcode_hint": "Code postal de l'arpenteur",
	"_Lot": "Lot",
    "_Lot_title": "No. Lot",
    "_Lot_title_hint": "Numéro de lot",
    "_Lot_description": "Description",
    "_Lot_description_hint": "Code cadastre et Designation Secondaire",
	"_Lot_category": "Partie de lot",
    "_Lot_category_hint": "O est partie de lot, N est Lot Complet",
	"_Lot_subcategory": "Mandat",
    "_Lot_subcategory_hint": "Numéro de Mandat",
	"_note_chart": "Notes",
	"_note_val_chart": "%@ notes"
});