SC.stringsFor('en', {
    "_Note": "Note",
    "_Note_title": "Title",
    "_Note_title_hint": "The note's title",
    "_Note_description": "Description",
    "_Note_description_hint": "The note's description",
    "_Road": "Road",
    "_Road_title": "Name",
    "_Road_title_hint": "The road's name",
    "_Road_description": "Description",
    "_Road_description_hint": "The road's description",
	"_Road_category": "Category",
    "_Road_category_hint": "Category",
	"_Road_subcategory": "Sub Category",
    "_Road_subcategory_hint": "Sub Category",
	"_Hydro": "Hydrology",
    "_Hydro_title": "Name",
    "_Hydro_title_hint": "Entity's name",
    "_Hydro_description": "Description",
    "_Hydro_description_hint": "The hydro's description",
	"_Hydro_category": "Category",
    "_Hydro_category_hint": "Category",
	"_Hydro_subcategory": "Sub Category",
    "_Hydro_subcategory_hint": "Sub Category",
	"_Limit": "Limits",
    "_Limit_title": "Name",
    "_Limit_title_hint": "Limit's name",
    "_Limit_description": "Description",
    "_Limit_description_hint": "Limit's description",
	"_Limit_category": "Category",
    "_Limit_category_hint": "Category",
	"_Limit_subcategory": "Sub Category",
    "_Limit_subcategory_hint": "Sub Category",
	"_arpenteur_chart": "Surveyor",
	"_arpenteur_val_chart": "%@ surveyors",
	"_Arpenteur": "Surveyor",
	"_Arpenteur_firstname": "First Name",
	"_Arpenteur_firstname_hint": "Surveyor's first name",
	"_Arpenteur_lastname": "Last Name",
	"_Arpenteur_lastname_hint": "Surveyor's last name",
	"_Arpenteur_postalcode": "Postal Code",
	"_Arpenteur_postalcode_hint": "Surveyor's postal code",
	"_Lot": "Lot",
    "_Lot_title": "No. Lot",
    "_Lot_title_hint": "Lot Number",
    "_Lot_description": "Description",
    "_Lot_description_hint": "Code cadastre and Designation Secondaire",
	"_Lot_category": "Partie de lot",
    "_Lot_category_hint": "O is partie de lot, N is Complet",
	"_Lot_subcategory": "Mandat",
    "_Lot_subcategory_hint": "No Mandat",
	"_note_chart": "Notes",
	"_note_val_chart": "%@ notes"
});