SC.stringsFor('fr', {
    "_unknown": "- Inconnu -",
    "_layers": "Couches",
    "_search": "Recherche",
    "_edit": "Modifier",
    "_features_selected": "(%@ autres éléments sélectionnés)",
    "_close": "Fermer",
    "_zoom": "Zoom",
    "_delete": "Supprimer",
    "_cancel": "Annuler",
    "_confirmDelete": "Voulez-vous vraiment supprimer '%@' ?",
    "_google": "Google",
    "_results": "Résultats",
    "_google_tooltip": "Mettre Google comme couche principale",
    "_osm": "OSM",
    "_osm_tooltip": "Mettre Open Street Map comme couche principale",
    "_road": "Rue",
    "_satellite": "Satellite",
    "_terrain": "Terrain",
    "_hybrid": "Hybride",
    "_of": "%@ de %@",
    "_previous": "Précédent",
    "_next": "Suivant",
    "_map_select": "Sélection",
    "_map_edit": "Modifier",
    "_map_create": "Créer",
    "_createOption": "Mode de Création",
    "_pointCreate": "Point",
    "_lineCreate": "Ligne",
    "_polygonCreate": "Polygone",
    "_logout": "Déconnexion",
    "_Google": "Google",
    "_chartPage": "Graphiques",
    "_goToChart": "Aller à la page des graphique",
    "_locateTooltip": "Aller à votre position actuelle",
    "_layersTooltip": "Les couches de la carte",
    "_optionsTooltip": "Les options",
    "_loginTooltip": "L'usager connecté",
    "_selectionToolTooltip": "Sélectionner des élément sur la carte",
    "_editToolTooltip": "Modifier la topologie d'un élément sur la carte",
    "_createToolTooltip": "Créer une note sur la carte"
});
