SC.stringsFor('English', {
    "_users.Title": 'The Users',
    "_users.toggleToolTip": 'Switch to Users',
    "_users.Users": 'Users',
    "_users.NoSelection": "Select a User",
    "_users.Informations": "Informations",
    "_users.Security": "Security",
    "_users.Name": "Account",
    "_users.FullName": "FullName",
    "_users.Email": "Email",
    "_users.MoreInfo": "More Info",
    "_users.Password": "Password",
    "_users.NewPassword": "New Password",
    "_users.PasswordHint": "Min 5 characters",
    "_users.Confirm": "Confirm",
    "_users.Expire": "Expire",
    "_users.ExpireHint": "dd-mm-yyyy",
    "_users.ChangePassword": "Change Password",
    "_users.PasswordsDontMatch": "The passwords don't match.",
    "_users.addToolTip": 'Add a user',
    "_users.deleteToolTip": 'Delete the selected user',
    "_users.Create a new User": "Create a new User",
    "_users.1user": "1 user",
    "_users.MultipleUsers": "%@ users",
    "_users.Multiple (%@)": "- Multiple users (%@)",
    "_users.NoUser": "No user",
    "_users.ConfirmDeleteUser": "Do you really want to delete %@ ?",
    "_users.Change Password": "Change the Password",
    "_users.%@ days": "This password will expire in %@ days.",
    "_users.Never Expire Password": "This password will never expire.",
    "_users.Expired Password": "This password has expired.",
    "_users.Cant read expire date": "Cannot parse the date.",
	"_users.Roles" : "Roles (%@)",
	"_users.addRoles.Add Roles": "Add roles to this user",
	"_users.addRoles.Roles": "Roles:",
	"_users.addRoles.Add" : "Add",

    "_groups.Title": 'The Groups',
    "_groups.toggleToolTip": 'Switch to Groups',
    "_groups.Groups": 'Groups',
    "_groups.Name": 'Name',
    "_groups.cancel": 'Cancel',
    "_groups.cancelToolTip" : 'Cancel the changes',
    "_groups.save": 'Save',
    "_groups.saveToolTip" : 'Save the changes',
    "_groups.NoSelection": "Select a Group",
    "_groups.1group": "1 group",
    "_groups.MultipleGroups": "%@ groups",
    "_groups.Multiple (%@)": "- Multiple groups (%@)",
    "_groups.NoGroup": "No group",
    "_groups.ConfirmDeleteGroup": "Do you really want to delete the group %@ ?",
    "_groups.Members": "Members (%@)",
    "_groups.Privileges": "Privileges (%@)",
	"_groups.Create a new Group" : "Create a new Group",
	"_groups.addToolTip" : "Add a group",
	"_groups.deleteToolTip" : "Delete selected group",
	"_groups.addMembers.Add": "Add",
	"_groups.addMembers.Users": "Users",
	"_groups.addMembers.Add Members": "Add members to this group",
	"_groups.addMemberToolTip" : "Add a member to this group",
	"_groups.removeMemberToolTip" : "Remove selected members from this group",
	"_groups.addPrivileges.Add": "Add",
	"_groups.addPrivileges.Privileges": "Privileges",
	"_groups.addPrivileges.Add Privileges": "Add privileges to this group",
	"_groups.addPrivilegesToolTip": "Add a privilege to this group",
	"_groups.removePrivilegesToolTip": "Remove selected privileges",
	"_groups.Parent" : "Parent Group",

    "_OK": "OK",
    "_Cancel": "Cancel",
    "_Delete": "Delete",
	"_Create": "Create",
});
