SC.stringsFor('en', {
	"_unknown" : "- Unknown -",
	"_layers": "Layers",
	"_search": "Search",
	"_edit": "Edit",
    "_features_selected": "(%@ other features selected)",
	"_close": "Close",
	"_zoom" : "Zoom",
	"_delete" : "Delete",
	"_cancel" : "Cancel",
	"_confirmDelete": "Do you really want to delete '%@' ?",
	"_google" : "Google",
	"_results" : "Results",
	"_google_tooltip" : "Set Google as the main layer",
	"_osm" : "OSM",
	"_osm_tooltip" : "Set Open Street Map as the main layer",
	"_road": "Road",
	"_satellite": "Satellite",
	"_terrain": "Terrain",
	"_hybrid": "Hybrid",
	"_of": "%@ of %@",
	"_previous": "Previous",	
	"_next": "Next",
	"_map_select": "Select",
	"_map_edit": "Edit",
	"_map_create": "Create",
	"_createOption": "Create Mode",
	"_pointCreate": "Point",
	"_lineCreate": "Line",
	"_polygonCreate": "Polygon",
	"_logout": "Logout",
	"_Google": "Google",
	"_chartPage": "Charts",
	"_goToChart": "Go to the chart page",
	"_locateTooltip": "Go to your actual location",
	"_layersTooltip": "The map layers",
	"_optionsTooltip": "The options",
	"_loginTooltip": "The logged in user",
	"_selectionToolTooltip": "Select a feature on the map",
    "_editToolTooltip": "Edit the geometry of a feature on the map",
    "_createToolTooltip": "Create a note on the map"
});